homedir: /home/user
user: user
docker-url: 127.0.0.1:2375
docker-image: slurm-debian
docker-hostname: "linux0"
docker-startup-root-cmds:
    - service munge start
    - service slurmd start
    - service slurmctld start
websocket-host: "127.0.0.1"
motd: ""
