homedir: /home/user
user: user
docker-url: 127.0.0.1:2375
docker-image: slurm-debian
docker-hostname: "linux0"
docker-startup-root-cmds:
    - service munge start
    - service slurmd start
    - service slurmctld start
websocket-host: "127.0.0.1"
motd: |
    Welcome to the SLURM learning terminal
    The terminal is very limited and will only provide you with enough tools to help you learn how to use slurm.
    Running time on the queue is also very limited as this is not the place to run your experiments.
